### ISSUE TITLE
Статус решения как ссылка

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#10]
Почему при наведении на статус решения курсор меняется на ссылочный? При наведении на "скачать" - это логично, ведь иы скачиваем, а при чем тут сатус решения?
![image](https://user-images.githubusercontent.com/12235437/95171956-863d6e00-076b-11eb-885a-9e8b614ba190.png)

**Comment by IvLaptev** [comment]
Просто поставил им один класс
