### ISSUE TITLE
Фавиконка

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#14]
На сайте используется стандартная иконка, необходимо создать и применить новую.

Сама иконка ожидается от @AlterJD

**Comment by AlterJD** [comment]
Для фавиконки использовать файл favicon.svg из папки Icons_olympiad, к которой у Вани есть доступ.

**Comment by CAPCHIK** [comment]
@IvLaptev  Тогда добавь её таки)
