### ISSUE TITLE
Обновление статуса через SignalR

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#16]
Сейчас обновление статуса сданных задач происходит через множество запросов про каждое решение, что негативно сказывается на сервере при большом количестве клиентов, и в целом не является хорошекй практикой.

На сервере реализован хаб уведомлений на SignalR, его применение на C# выглядит следующим образом:
```csharp
using Microsoft.AspNetCore.SignalR.Client;
using System;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace SignalROlympiadTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            
            var connection = new HubConnectionBuilder()
                .WithUrl("http://localhost:5501/api/hubs/solutionStatus", options =>
                {
                    options.AccessTokenProvider = async () =>
                    {
                        var httpClient = new HttpClient();
                        var loginResponse = await httpClient.PostAsync("http://localhost:5501/api/auth/login",
                            new StringContent(JsonSerializer.Serialize(new { login = "admin@localhost.ru", password = "VeryStrongPass1" }), Encoding.UTF8, "application/json"));
                        var stringResponse = await loginResponse.Content.ReadAsStringAsync();
                        var loginInfo = JsonDocument.Parse(stringResponse);
                        return loginInfo.RootElement.GetProperty("Token").GetString();
                    };
                })
                .WithAutomaticReconnect()               
                .Build();
            connection.On<UpdateSolutionStatusModel>("UpdateSolutionStatus", ussm =>
            {
                Console.WriteLine($"Updated sol {ussm.Id} to {ussm.Status}");
            });
            connection.On<UpdateExerciseStatusModel>("UpdateExerciseStatus", uesm =>
            {
                Console.WriteLine($"Updated ex {uesm.ExerciseId} to {uesm.ExerciseStatus}");
            });
            connection.On<string>("InformationMessage", message =>
            {
                Console.WriteLine($"Message: {message}");
            });
            await connection.StartAsync();
            Console.WriteLine("started, press [enter] to end");
            Console.ReadLine();
        }
    }
    public class UpdateExerciseStatusModel
    {
        public Guid ExerciseId { get; set; }
        public SolutionStatus ExerciseStatus { get; set; }
    }
    public class UpdateSolutionStatusModel
    {
        public Guid Id { get; set; }
        public string Language { get; set; }
        public Guid UserId { get; set; }
        public Guid ExerciseId { get; set; }
        public SolutionStatus Status { get; set; }
        public DateTime SendingTime { get; set; }
        public DateTime? StartCheckingTime { get; set; }
        public DateTime? CheckedTime { get; set; }
    }

    public enum SolutionStatus
    {
        ErrorWhileCompile,
        CompileError,
        RunTimeError,
        WrongAnswer,
        TooLongWork,
        InQueue,
        InProcessing,
        Successful
    }
}
```

На JS применение будет выглядеть аналдогичным образом, необходимо реализовать реконнект, и при получении соответствующих событий изменять контент на сайте.

Есть три возможных события:

1. UpdateSolutionStatusModel - обновление статуса конкретного решения
2. UpdateExerciseStatus - обновление статуса конкретного задания (сделано для возможности менять цвет кружков в верхней левой части экрана, например)
3. InformationMessage - любое строковое сообщение, которое необходимо отобразить пользователю. Например сейчас по этому событию через 30 секунд после логина приходит сообщение о необходимости сменить пароль, если вход был произведен через стандартные логин пароль из конфигурации (реализация сброса пароля запрошена в #13)

**Comment by CAPCHIK** [comment]
Документация по JS библиотеке доступна тут https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1

**Comment by CAPCHIK** [comment]
Есть даже на русском https://docs.microsoft.com/ru-ru/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1

**Comment by IvLaptev** [comment]
Для SignalR будет использоваться только WebSocket?

**Comment by CAPCHIK** [comment]
А, ну так давай сделаю доступ к core
Это гибче

**Comment by CAPCHIK** [comment]
15 минут подождёшь?

**Comment by IvLaptev** [comment]
Да

**Comment by CAPCHIK** [comment]
Добавил  localhost:4200 и 127.0.0.1:4200 https://github.com/RTUITLab/Olympiad-Back/commit/bac0aefc05dd112465c1685f60e39545a93a4ee2

**Comment by CAPCHIK** [comment]
Скоро будет доступке docker образ, сможешь скачать , жди как среднее будет зеленым
https://dev.azure.com/rtuitlab/RTU%20IT%20Lab/_build/results?buildId=2746&view=results

**Comment by IvLaptev** [comment]
Да, теперь работает

**Comment by IvLaptev** [comment]
У меня все эти сигналы работают, но немного смущают две вещи:
+ в SolutionStatus приходит обычный Solution, только названия всех полей почему-то с маленькой буквы, из-за чего приходится вводить новую модель, и конвертировать полученные Solution;
+ в том же SolutionStatus приходят странные даты. Если везде они поступают как время по Гринвичу, то в этом случае я их принимаю как местное время. Конечно, у меня решается эта проблема добавлением 'Z' к исходной строке даты.

Всё вышеперечисленное как-то будет меняться в дальнейшем или оставляем как есть?

**Comment by CAPCHIK** [comment]
Это мой косяк, забыл про то, что конфигурация http ответов не распространяется на signalr

Время сделаю, чтобы приходило с Z.

А вот с json иначе. Я предлагаю сделать так, чтобы везде приходили с маленькой, ибо это так-то больше формат json и js

**Comment by IvLaptev** [comment]
Тогда я Z убираю.

Ну а с json, пусть будет все с маленькой. Сегодня ночью тогда запушу это.

**Comment by CAPCHIK** [comment]
Ок, к вечеру будет

**Comment by CAPCHIK** [comment]
Сделал json  в camelCase, ожидаемо теперь фронт теперь не работает

**Comment by CAPCHIK** [comment]
Пока откатил на предыдущую версию, как будет готово на фронте - выкачу одновременно и сервер

**Comment by IvLaptev** [comment]
Я сделал, даже залил только что. Дело в том, что я стал проверять, и что-то не работает. Точнее сервер у меня перестал проверять задания, и не присылает изменения статусов. Я собственно, всё это время пытаюсь понять, что не так.

**Comment by CAPCHIK** [comment]
Сделай docker pull, и запусти снова. Я забыл в сервисе проверяторе поменять `Token` на `token`
