### ISSUE TITLE
Заглушки на местах загрузки

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#18]
Если интернет медленный - при открытии соревнования и или задания очень долго открывается контент (0,7 секунд и более). Необходимо на время ожидания информации рендерить какую-то анимацию загрузки. 

В идеале рендерить макет того, что будет отображаться, и потом его наполнить данными. Второй случай надо будет дизайнить, а просто анимацию достать с запускать в местах подгрузки интерфеса можно сделать и сейчас.

**Comment by CAPCHIK** [comment]
Не закрылось это issue из-за того, что слово solved - не ключевое
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

А вообще-то - заглушки не хватает при открытии соревнования)

**Comment by IvLaptev** [comment]
Вот так бы сразу)

**Comment by CAPCHIK** [comment]
Я не проверяю наличие коммита каждые 5 минут. Можешь кидать PR по каждому фиксу - и Issue указывать в нем, так я буду получать  уведомления

**Comment by IvLaptev** [comment]
Я вижу, как ты это делаешь, вылетело из головы, что вместо resolved написал solved.
