### ISSUE TITLE
Заглавные буквы в шрифте

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#2]
Заметил, что при рендере названий заданий при открытии соревнования заглавная буква как бы посередине текста, это так по дизайну? @AlterJD

**Comment by CAPCHIK** [comment]
Вот, "Увеличение числа"

**Comment by CAPCHIK** [comment]
Хотя, при добавлении новых заданий видно, что такая бага идет именно с буквой У. Это такой шрифт?
![image](https://user-images.githubusercontent.com/12235437/94926651-f3a08480-0475-11eb-9334-d8207fdc67ff.png)

**Comment by AlterJD** [comment]
Да, это такой шрифт
