### ISSUE TITLE
Переимнование файлов при сборке

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#21]
Есть идея именовать файлы (js, css) сборки в соттветствии с номер сборки. Так новые обновления будут приходить клиентам быстрее, ведь браузеры кешируют по имени файла.

Еще поищу про это информацию, приложу в комменты.

**Comment by IvLaptev** [comment]
Скорее всего новые обновления быстрее приходить не будут, так как мы это и так используем. Единственное, файлы скриптов и стилей содержат не номер сборки, а свои хэши, которые webpack выставляет дефолтно.
#### Пример:
+ Просто билд
![b1](https://user-images.githubusercontent.com/23360152/95609841-10d1e600-0a68-11eb-8150-e4253f2e2321.PNG)
+ Добавим две строчки в один из файлов
![b2](https://user-images.githubusercontent.com/23360152/95609891-221af280-0a68-11eb-9e90-8ec1a73f99d8.PNG)

**Comment by CAPCHIK** [comment]
Хм, окей. Значит пока на это забьем
