### ISSUE TITLE
Требования к сдаваемым решениям

### ISSUE THREAD

**Issue by IvLaptev** [RTUITLab/Olympiad-Front#22]
Я подумал, куда и как можно поместить требования к программам.
Вот результат работы мысли

![Rule Screen](https://user-images.githubusercontent.com/23360152/95679658-ff5e1a80-0bdc-11eb-955b-d62ce01cc69e.png)

**Comment by CAPCHIK** [comment]
Лично мне нравится, ждём ответа от @AlterJD

**Comment by AlterJD** [comment]
С оформлением согласна

**Comment by CAPCHIK** [comment]
Добавил текста в папку temp отдельной ветви
https://github.com/RTUITLab/Olympiad-Front/tree/langs-info/temp
