### ISSUE TITLE
Наложение названий

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#32]
Сейчас если название соревнования слашком большое - задание слезает под него, это нормальное поведение.
Но при открытии списка заданий названия накладываются друг на друга и превращаются в кашу.

![image](https://user-images.githubusercontent.com/12235437/96966072-0846ca00-14c2-11eb-8f75-af79d75dc2ac.png)

![image](https://user-images.githubusercontent.com/12235437/96966088-0f6dd800-14c2-11eb-924e-c5e01a90c786.png)

**Comment by IvLaptev** [comment]
Решено
