### ISSUE TITLE
Необходимость слова "Описание"

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#33]
@AlterJD  Нужно ли здесь вообще слово описание? Мне кажется и так понятно, что идет справочная информация. Особенно странно выглядит на более громоздеом описании.

![image](https://user-images.githubusercontent.com/12235437/96966985-a5563280-14c3-11eb-8b01-ffc3a51f387c.png)

**Comment by AlterJD** [comment]
Считаю, что да, поскольку описания соревнований могут быть разными.

**Comment by CAPCHIK** [comment]
Так или иначе это слово мало мешает
