### ISSUE TITLE
Нельзя скачать последнее решение

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#39]
При открытии задания, если есть решения, решение можно скопировать, но скачать нельзя, кнопка ведет на пустую js функцию

![image](https://user-images.githubusercontent.com/12235437/97092133-36c5c180-15f6-11eb-8872-07dbcce947b7.png)
![image](https://user-images.githubusercontent.com/12235437/97092128-1bf34d00-15f6-11eb-9567-fec6a43667e6.png)

**Comment by CAPCHIK** [comment]
И тогда в итоге три задания по этим кнопкам
* Починить скачивание
* Добавить всплывающие подсказки, как к статусам решения
* При отсутствии решений не рисовать эти кнопки вовсе

**Comment by IvLaptev** [comment]
Подсказки с текстом Скачать и Копировать, или что-то другое?
