### ISSUE TITLE
Прозрачный фон

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#4]
Нужен ли прозрачный фон в выпадающих меню?
![image](https://user-images.githubusercontent.com/12235437/94926494-c0f68c00-0475-11eb-9182-a2e74827f89f.png)
Кажется, он тольео мешает в некоторых местах, например в списке заданий

**Comment by AlterJD** [comment]
Ладно, логично здесь конкретно убрать прозрачность

**Comment by CAPCHIK** [comment]
@IvLaptev Теперь это твоя задачка
