### ISSUE TITLE
Уезжает окно с кодом

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#41]
При горизонтальном скролле окно уезжает вместе с кодом. Хотя должно оставаться на своем месте. Как минимум это относится к верхней строке, но возиожно стоит и номера строк не убирать.
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/12235437/97096381-35a98a00-1620-11eb-8ef0-5607fdfd716e.gif)

**Comment by IvLaptev** [comment]
Я уже немало думаю об этом. Сейчас, наверное, только как-то так с помощью переносов можно что-то сделать.

![code](https://user-images.githubusercontent.com/23360152/97100025-85c83100-16a0-11eb-9c0e-844d9aad2abb.PNG)
