### ISSUE TITLE
При наведении на кнопку "Инструкция" не появляется ссылка на эту страницу

### ISSUE THREAD

**Issue by 0ReC0** [RTUITLab/Olympiad-Front#43]
![image](https://user-images.githubusercontent.com/41593670/97117739-c82c5500-1716-11eb-8900-37d8441aff4b.png)
Не появляется снизу слева ссылка на страницу, на которую указывает кнопка
![image](https://user-images.githubusercontent.com/41593670/97119332-8f917900-1720-11eb-8975-6c47c865eb6b.png)

**Comment by IvLaptev** [comment]
@0ReC0, а на остальных как?

**Comment by CAPCHIK** [comment]
Возможно дело в браузере. Открываешь в сафари?

**Comment by IvLaptev** [comment]
Нет, дело не в этом

**Comment by 0ReC0** [comment]
> Нет, дело не в этом

Да, я просто не понимаю зачем мне кнопка "инструкция", если я уже в инструкции автоматически когда захожу на сайт

**Comment by 0ReC0** [comment]
> Возможно дело в браузере. Открываешь в сафари?

Я понял, почему не отрабатывает, потому что на кнопке стоит обработчик скорее всего в ts, а не в html с помощью routerLink, он переводит на компонент overview

**Comment by IvLaptev** [comment]
На кнопке стоит именно routerLink, который и не даёт переходить, так как это и не нужно, ведь ты уже находишься там, куда ведёт ссылка.

**Comment by 0ReC0** [comment]
> На кнопке стоит именно routerLink, который и не даёт переходить, так как это и не нужно, ведь ты уже находишься там, куда ведёт ссылка.

Зачем мне эта кнопка на начальном экране если я там уже нахожусь автоматически ?

**Comment by CAPCHIK** [comment]
А в чем именно дело?
Я верно понимаю, что находясь на странице с инструкцией, тебя не устраивает, что при нажатии кнопки "инструкция" ничего не происходит?

Как тогда при открытой странице с сообщениями ВКонтакте должен обрабатывать нажатие на кнопку "мессенджер"? 

Я не конца понимаю собственно проблему

**Comment by 0ReC0** [comment]
> А в чем именно дело?
> Я верно понимаю, что находясь на странице с инструкцией, тебя не устраивает, что при нажатии кнопки "инструкция" ничего не происходит?
> 
> Как тогда при открытой странице с сообщениями ВКонтакте должен обрабатывать нажатие на кнопку "мессенджер"?
> 
> Я не конца понимаю собственно проблему

Теперь проблема заключается в том, что не появляется снизу слева ссылка
![image](https://user-images.githubusercontent.com/41593670/97119332-8f917900-1720-11eb-8975-6c47c865eb6b.png)

**Comment by CAPCHIK** [comment]
В рамках текущей системы, где нет необходимости в обеспечении жёсткой accessibility - данный функционал не необходим.
