### ISSUE TITLE
Проблема с шапкой, расположение, видимость текста

### ISSUE THREAD

**Issue by 0ReC0** [RTUITLab/Olympiad-Front#44]
Шапки отличаются расположением надписи, от этого становится не видно надписи белыми буквами и не понятно вообще с чего это она теперь резко лево align вместо центр align.  Следует либо изменить цвет шрифта или сделать менее яркую шапку.
![image](https://user-images.githubusercontent.com/41593670/97117882-a5e70700-1717-11eb-8618-454c1cb52ffa.png)
![image](https://user-images.githubusercontent.com/41593670/97117886-aed7d880-1717-11eb-8a51-7799324ba726.png)

**Comment by IvLaptev** [comment]
@AlterJD, что скажешь?
