### ISSUE TITLE
Волны

### ISSUE THREAD

**Issue by IvLaptev** [RTUITLab/Olympiad-Front#5]
## Лучше не стало
@AlterJD, я сделал из волн svg, но теперь по-моему картинка стала слишком чёткой. Что с этим делать?
### Примеры
+ Втиснуты в ширину экрана
![1](https://user-images.githubusercontent.com/23360152/95023555-5ff1d280-0686-11eb-8c8d-58240f00e848.PNG)
+ 150% исходного размера
![2](https://user-images.githubusercontent.com/23360152/95023558-6122ff80-0686-11eb-8db6-8c7d51c467df.PNG)
+ 200% исходного размера
![3](https://user-images.githubusercontent.com/23360152/95023559-6122ff80-0686-11eb-9eb9-f329c6f69ab9.PNG)

**Comment by AlterJD** [comment]
Добавить изображению волн параметр opacity 70%. Думаю, этого должно хватить, если нет, то играть с этим параметром, пока волны не станут менее вырвиглазными.

**Comment by IvLaptev** [comment]
Я сделал линии толще и прозрачнее на 87%, получилось как на рисунке. @AlterJD, получилось хорошо, или надо ещё менять?

![waves](https://user-images.githubusercontent.com/23360152/95675605-31fa1a00-0bc1-11eb-90fa-4d9c2adcd275.png)

**Comment by AlterJD** [comment]
Да, думаю, оставляй так)
