### ISSUE TITLE
monospace font

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#50]
Для примерров ввода вывода **необходимо** использовать моноширинный шрифт, для того чтобы такой контент
![image](https://user-images.githubusercontent.com/12235437/106768915-48edcd80-65f1-11eb-9517-eb2294674c3f.png)
Не превращался в такой
![image](https://user-images.githubusercontent.com/12235437/106768959-51de9f00-65f1-11eb-8d72-2a79eea6983a.png)

**Comment by IvLaptev** [comment]
С третьего раза решилось
