### ISSUE TITLE
Line numbers selecting

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#51]
Сейчас при попытке выделить линии выделяются и номера строк, необходимо их игнорировать при выделении
![image](https://user-images.githubusercontent.com/12235437/106771607-024da280-65f4-11eb-9c40-df3a192f3ab5.png)

**Comment by IvLaptev** [comment]
Closed in [c1402a7](https://github.com/RTUITLab/Olympiad-Front/commit/c1402a7ec249aadb7e6e5c9f57ecc7cf5d5b4805)
