### ISSUE TITLE
Bad title

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#54]
Необходимо вписать верное название, какое - посмотреть в старом коде

![image](https://user-images.githubusercontent.com/12235437/110111820-c24e1c80-7d65-11eb-8dd9-6f0d21e99d2f.png)

**Comment by CAPCHIK** [comment]
Из-за этого кстати нет меню с аккаунтом, сменой пароля, информацией, ссылкой на админку

**Comment by IvLaptev** [comment]
Решено
