### ISSUE TITLE
Show build logs

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#55]
В API есть маршрут `/api/Check/buildlogs/{solutionId}` который возвращает логи сборки для отправленного решения в красивом виде, в таком виде их можно отображать пользователям.

Необходимо их показывать для каждого решения, для которого захочет пользователь. Если логов нет - вернется пустой список. Произойти это может если, например решение еще в очереди. В целом, если решение в очереди или на проверке - статус показывать нет смысла, так как еще нет решения. Соответственно и кнопку можно убрать.

**Comment by IvLaptev** [comment]
Вот так раскрывается при нажатии на статус

![image](https://user-images.githubusercontent.com/23360152/110473199-5108c380-80ef-11eb-9ce8-d24d313e63cc.png)

**Comment by CAPCHIK** [comment]
Заметил что при таком рассмотрении можно потеряться, к чему именно относятся данные логи. Есть мысли как это можно изменить? У меня пока нет
![image](https://user-images.githubusercontent.com/12235437/110481009-f42fed80-809b-11eb-991d-e35126cccea5.png)

**Comment by IvLaptev** [comment]
Можно сделать так. Вопроса, к какому решению это относится точно не будет.

![image](https://user-images.githubusercontent.com/23360152/110485218-764ffe80-80fc-11eb-862a-d4a6df89949d.png)

**Comment by CAPCHIK** [comment]
Мне кажется так лучше, да. Впоследствии сборщик будет прикладывать версию самого себя, и будет вообще отлично

**Comment by CAPCHIK** [comment]
В плане это поле добавится

**Comment by IvLaptev** [comment]
Поле с датой?

**Comment by CAPCHIK** [comment]
Что поле с датой?

**Comment by IvLaptev** [comment]
С этим закончили?

**Comment by CAPCHIK** [comment]
Да, думаю сделано отлично, и смерджено было в коммите 8f28a3b87e36be512f7b75237932fb0aa9050297
