### ISSUE TITLE
Code block style updates

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#59]
Убавить расстояние до первого символа в строке, перед строкой `using` нет пробелов, можно этот отступ сделать меньше.

Номера строк "упираются" в вертикальную линию, необходимо отодвинуть их левее.
![image](https://user-images.githubusercontent.com/12235437/111015157-4737c800-835c-11eb-8f7b-74f7da440b79.png)

**Comment by IvLaptev** [comment]
![image](https://user-images.githubusercontent.com/23360152/111171271-d25fca80-85b5-11eb-8533-8ab486ba6735.png)

Такие отступы лучше?

**Comment by CAPCHIK** [comment]
Определенно до
