### ISSUE TITLE
Skip days in time left

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#69]
В сообщении сколько осталось времени до конца соревнования при наличии дней они просто игнорируются, что не есть хорошо на примере многомесячного соревнования
![image](https://user-images.githubusercontent.com/12235437/139644305-b73cf4e3-8457-4ae3-b81d-caf32625ab2f.png)

**Comment by IvLaptev** [comment]
Выполнено [58ddb84](https://github.com/RTUITLab/Olympiad-Front/commit/58ddb84fd3b1b8917300366e2b563cc3ffb3367e)
