### ISSUE TITLE
Login return

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#70]
Для панели управления написала логика, при которой пользователь перенаправляется на страницу `/login` с параметром `returnTo`, в котором содержится относительный путь для страницы, которую необходимо открыть после логина

Необходимо как минимум организовать такое поведение для control-panel, а в идеале - для всех страниц пользовательской части системы олимпиады

**Comment by IvLaptev** [comment]
Я не понял. Каким образом, внося изменения в этом репе, я буду влиять на поведение панели управления?

**Comment by CAPCHIK** [comment]
Так и не нужно влиять на поведение панели управления

Попробуй в инкогнито перейти на dev control panel

Она предложит войти, и ты окажешься по адресу  `/login`, это обычный сайт, но в url будет параметр `returnTo`, так этот сайт сможет понять, что после логина надо перекидывать не на `/overwiew`, а куда указано в параметре
