### ISSUE TITLE
Режим тестирования

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#8]
Необходимо сделать режим тестирования, в котором будут только следущие статусы
Ошибка при компиляции
Решение в очереди на проверку
Решение проверяется
Решение **принятно**

То есть при такой системе сдающий не должен знать, как именно отработала его программа, а просто видеть, что решение принято.

Данную информацию предлагается брать с сервера, то есть завести еще один статус для решения.

Необходимо на странице с инструкцией описать, сто существует отдельный статус, либо объяснять это на странице информации соревнования, пока не знаю.

**Comment by IvLaptev** [comment]
То есть, сервер мне даёт информацию о том, что соревнование - это тест, а также присваивает особый статус решениям, которые были скомпилированы?

**Comment by CAPCHIK** [comment]
Почти
Сейчас статусы есть вот такие 
https://www.github.com/RTUITLab/Olympiad-Back/tree/master/Shared%2FModels%2FSolutionStatus.cs

А будет ещё один - Решение принято

Его сервер будет выдавать сам, если видит, что данный человек не должен видеть результат

То есть под капотом все как обычно, но клиент узнает только о том, что приняли, и как-то обработают

**Comment by IvLaptev** [comment]
Уже есть определённая уверенность в том, как будет выглядеть новый статус? Или хотя бы его код. У меня, конечно, есть предположение, что это будет 8, но хочется знать наверняка.

**Comment by IvLaptev** [comment]
### @CAPCHIK, какой номер будет иметь новый статус?
