### ISSUE TITLE
Некорректные кнопки в окне просмотра кода

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Olympiad-Front#9]
При нажатии кнопки скачать при пустом редакторе в консоль выводитсяо ошибка.
![image](https://user-images.githubusercontent.com/12235437/95171373-a7518f00-076a-11eb-8c7a-b73f55234610.png)
Да, пользователь это не увидит, но на самом деле ведь это не ошибка, а не обработанная должным образом ситуация.

**Comment by CAPCHIK** [comment]
Аналогично при копировании 
![image](https://user-images.githubusercontent.com/12235437/95171525-db2cb480-076a-11eb-88e3-e2a7a7ac250e.png)

**Comment by IvLaptev** [comment]
На самом деле ситуации совсем разные. Первое было специально, а второе действительно не заметил
